name: test1

trigger:
- master

pool: dev

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    hostname
    touch /home/ubuntu/1.txt
    touch /tmp/2.txt
    date
    
  displayName: 'Run a multi-line script'
