name: test1

trigger:
- master

pool: dev

steps:
- script: echo Hello, world123!
  displayName: 'Run a one-line script'

- script: |
    hostname
    touch /home/ubuntu/1.txt
    touch /tmp/2.txt
    date
    df -h
    echo "Hello1" > /home/ubuntu/1.txt
    
  displayName: 'Run a multi-line script'
